---

- name: Install docker on hosts
  hosts: Cluster_k8s
  become: yes

  tasks:
    - name: Update apt packages                                                              #apt-get update
      ansible.builtin.apt:
        update_cache: yes

    - name: Install packages                                                                 #Instal packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common

    - name: Add Docker GPG key                                                               #Add Docker's official GPG key:
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        update_cache: yes

    - name: Install Docker CE                                                                    #Install docker
      ansible.builtin.apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Ensure Docker is running and enabled                                                 #Start docker service
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add current user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes

    - name: Verify Docker installation                                                           #show docker version
      ansible.builtin.command: docker --version
      register: docker_version
      changed_when: false

    - name: Show Docker version
      ansible.builtin.debug:
        var: docker_version.stdout
