---

- name: Install k8s on hosts
  hosts: Cluster_k8s
  become: yes

  tasks:
    - name: Create directory for apt keyrings if not exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download and install Kubernetes GPG key
      ansible.builtin.shell: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      args:
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Set proper permissions for GPG key
      ansible.builtin.file:
        path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        mode: '0644'

    - name: Add Kubernetes repository
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/kubernetes.list
        content: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /"
        mode: '0644'

    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Kubernetes packages
      ansible.builtin.apt:
        name:
          - kubelet
          - kubeadm
          - kubectl

    - name: Hold Kubernetes packages at current version
      ansible.builtin.command:
        cmd: apt-mark hold kubelet kubeadm kubectl
        creates: /etc/apt/preferences.d/kubernetes.pref

    - name: Verify installation
      ansible.builtin.command:
        cmd: kubectl version --client
        register: kubectl_version
      changed_when: false

    - name: Show kubectl version
      ansible.builtin.debug:
        var: kubectl_version.stdout_lines
