---
- name: Install Apache and Upload my Web Page
  hosts: all
  become: yes

  vars:
    source_file: ./MyWebSite/index.html
    desti_file: /var/www/html

  tasks:
  - name: Install appache web Server
  - apt: name=apache2 state=latest

  - name: copy myHomePage to Servers
    copy: src={{ source_file }} dest={{ desti_file }} mode=0555
    notify: Restart Apache

  - name: Start webServer and make it enable on boot
    service: name=apache2 state=started enabled=yes

  handlers:
  - name: Restart Apache
    service: name=apache2 state=restarted
