# Тут мы работаем с циклом loop

---
- name: Loops Playbook
  hosts: ansibleclient3
  become: yes


  tasks:
  - name: Say Hello to ALL                                       # Делаем вывод item, которые описаны в блоке loop 
    debug: msg="Hello {{ item }}"
    loop:
        - "Vasya"
        - "Petya"
        - "Masha"
        - "Olya"

  - name: Loop Until example                                    # Тут делается запись символа "Z" в файл myfile.txt и вывод этого файла. Пока вывод не будет равен "ZZZZ" или до 10 раз, с задержкой в 2 секунды
    shell: echo -n Z >> myfile.txt && cat myfile.txt
    register: output                                            # Вывод 
    delay: 2                                                    # Задержка
    retries: 10                                                 # Попытки
    until: output.stdout.find("ZZZZ") == false

  - name: Print Final output
    debug:
      var: output.stdout                                        # Вывод результата
