# Тут используется includes. Что бы запускать в ansible_playbook, другие playbookи. Запускаем пинг и 2 других playbook

---

- name: add ansible user
  hosts: all
  become: yes

  vars:
   mytext: "Privet ot Andrey Gurenich"

  tasks:
  - name: Ping test

    include_tasks: create_folders.yml
    include_tasks: create_files.yml
