---

- name: My Super Playbook
  hosts: all
  become: yes

  vars:
   mytext: "Privet ot Andrey Gurenich"

  tasks:

  - name: Unregister Server from Load Balancer
    shell: echo This server {{ inventory_hostname }} was deregistered from our Load Balancer, node name is {{ ansible_nodename }} >> /home/log.txt
    delegate_to: 127.0.0.1

  - name: Create file1
    copy:
      dest: /home/file1.txt
      content: |
        This is FileN1
        On ENGLISH Hello World
        On RUSSIAN {{ mytext }}
    delegate_to: ansibleclient3

  - name: Create file2
    copy:
      dest: /home/file2.txt
      content: |
         This is FileN2
         On ENGLISH Hello World
         ON RUSSIAN {{ mytext }}

  - name: restart the machine
    shell: "sleep 5 && reboot"

    async: 1
    poll: 0

  - name: wait for the machine to come back online
    wait_for_connection:
      connect_timeout: 60
      sleep: 5
      delay: 5
      timeout: 300
    delegate_to: 127.0.0.1 
