---
- name: Swapoff enable and reboot host
  hosts: Cluster_k8s_new                                   #Used in a group
  become: yes                                          #root rights

  tasks:
    - name: Ping test                                  #Run a ping to make the host available
      ping:

    - name: Replace /swapfile with #/Я тут выключаю SWAP. Просто меняю /swapfile на #/swapfile в файле
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '(\s)/swapfile(\s)'
        replace: '\1#/swapfile\2'
        backup: yes
      register: fstab_changed

    - name: out results                                                                  # Смотрю результат по отключённому SWAP
      debug:
        var: swap_result.stdout

    - name: Create /etc/modules-load.d/k8s.conf with overlay and br_netfilter               #Загружаю модули overlay и br_netfilter в ядро
      ansible.builtin.copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter
        mode: '0644'

    - name: Ensure /etc/sysctl.d/k8s.conf exists with correct settings                    #Пишу в файл следующие значения, для разрешения в файервол
      ansible.builtin.copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1

    - name: Reboot host                                #Перезагружаю хост. Это надо для того, что бы применились настройки отключенного SWAP
      ansible.builtin.reboot:
        msg: "reboot Start"                            #Outputting a message to a remote host
        connect_timeout: 5                             #connection timeout
        reboot_timeout: 600                            #total reboot wait time
        pre_reboot_delay: 0                            #pre-reboot delay
        post_reboot_delay: 30                          #post-reboot delay before availability check

    - name: Power on host
      wait_for_connection:                             #Notification about host enabled
        delay: 10
        timeout: 300
